### ISSUE TITLE
Questions about the function calculate_phase_and_cyclic_error

### ISSUE THREAD

**Issue by 1134128371** [ksonod/itof_cyclic_error_simulator#1]
Hi, excellent work! The program finishes the simulation of TOF camera wiggling error, but I have some questiones about the function(calculate_phase_and_cyclic_error). First of all, in this function, to compute the DFT in sampled_corr_signal, and then the phase angle (frequency domain) is calculated by DFT. Why choose one of the phase angles as simulated_phase?

**Comment by ksonod** [comment]
Thank you for your comment and question, @1134128371. I suppose your question is related to L127 of ./functions/signal.py:  
`np.angle(fft_sampled_corr_signal)[1]`   
Here, the first element is selected because it corresponds to the first order harmonic.

**Comment by 1134128371** [comment]
emm..... ,Sorry I found it is difficult for me to understand(Perhaps It take up some of your time).Can you please give an email for communication (won't waste too much time，or my email "fengxiaowei@buaa.edu.cn").The main question is still about the L125 to L136(I tried to explain this logicallly, But I'm finding it harder and harder to explain.)
In the Setup Parameters section, you solved for the true phase at each distance, then solved for the cross-correlation function for the different phase delays, by extracting the four cross-correlations corresponding to each time sampling point, and then restoring the true phase. I was thinking about it myself last week, and I still don't understand something either: the true phase corresponds at each distance, but shouldn't the resulting simulated phase get 0 in the absence of phase delays due to distance? But the actual is a trigonometric function (that is, the problem with the actual result obtained, hmmm... . the ToF camera measures the distance by measuring the phase difference, but here the output at a certain phase is trigonometric)? There is also the question of the reduction method, I mainly refer to the article by Rapp [2007], but it's hard to find to explain it (probably based on a sine wave)

**Comment by 1134128371** [comment]
I'm really sorry to trouble you.

**Comment by ksonod** [comment]
> Can you please give an email for communication    

I prefer having discussion here to communicating through my personal e-mail. I am sorry for any inconvenience, and thank you for your understanding. 
.  

> The main question is still about the L125 to L136.  

The first part is to apply Fourier transform to correlation signal and to select the first order harmonic. In the second part, phase wrapping is corrected, and phase error is calculated simply by:
`cyclic_error = simulated_phase - self.simulation_data.gt_phase`
.  

> the ToF camera measures the distance by measuring the phase difference, but here the output at a certain phase is trigonometric.      

My apologies in advance if I incorrectly interpret your statement. One simulated phase value corresponds to one ground-truth depth or ground-truth phase. However, the simulated phase is typically suffered from the wiggling error, which is also known as cyclic error, because of aliasing. With this simulator, you can obtain multiple simulated phase values at different ground-truth phases. If you plot phase error (i.e., the difference between simulated phase and ground-truth phase) against ground-truth phase, you will see the wiggling error, which follows a cyclic pattern.  

If the concept of the wiggling error is not clear to you, you can refer to the [article](https://medium.com/chronoptics-time-of-flight/harmonic-aliasing-wiggle-error-in-indirect-time-of-flight-depth-cameras-efa1632d4d1b) by Chronoptics.

**Comment by ksonod** [comment]
If there are no further questions, I will close this thread soon.

**Comment by 1134128371** [comment]
I appreciate the help you've provided, and based on previous chats have resolved the existing confusion. Thank you very much.

**Comment by ksonod** [comment]
You are welcome.
